#!/bin/sh

source ~/.theme_selected

# funcoes cliclaveis
case $BUTTON in
    4) bash ~/.config/suckless/scripts/dwm/dwm-brilho-tela-aumenta ;;
    5) bash ~/.config/suckless/scripts/dwm/dwm-brilho-tela-diminui ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac

brilho=$(brightnessctl | awk '/%/ {print$4}' | cut -c 2-4 | sed 's/%//' | sed 's/)//')
brilhoIcone="^c$COLOR_2^󰃠 ^d^$brilho󰏰"

echo "$brilhoIcone  "
