#!/bin/bash

# Carrega função para aplicar o tema e o tema de cores
source ~/.config/suckless/scripts/dwmblocks/sb-carrega-tema-dwmblocks

## Carrega o brilho da tela
valor_brilho=$(brightnessctl | awk '/%/ {print$4}' | cut -c 2-4 | sed 's/%//' | sed 's/)//')

## Variaveis que serão passadas a função
icone="󰃠"
cor_forte=$COLOR_1
cor_fraca=$COLOR_9

## Antigo método antes dda função
# brilhoIcone="$icone_redshift^b$COLOR_1^^c$COLOR_BACKGROUND^ 󰃠 ^d^^c$COLOR_BACKGROUND^^b$COLOR_9^ $brilho ^d^"

# Monta o retorno do dwmblocks pela função aplicar_tema
brilhoIcone=$(aplicar_tema "$icone" "$valor_brilho" "$cor_forte" "$cor_fraca")

# Apresentacao condicionada
case "$OPERATION_MODE" in
    "MINIMO")
        echo ""
    ;;
    "MEDIO")
        echo ""
    ;;
    *)
        echo "$brilhoIcone"
    ;;
esac

# funcoes cliclaveis
case $BUTTON in
    4) bash ~/.config/suckless/scripts/dwm/dwm-brilho-tela-aumenta ;;
    5) bash ~/.config/suckless/scripts/dwm/dwm-brilho-tela-diminui ;;
    6) setsid -f st -e emacs -nw "$0" ;;
esac

exit 0
