#!/bin/bash

# Carrega informacoes do modo de operacao
arquivo_modo="$HOME/.cache/dwmblocks_modo_operacao"

if [ -f $arquivo_modo ]; then
    source $arquivo_modo
else
    OPERATION_MODE="COMPLETO"
fi

# Carrega o tema
source ~/.theme_selected


# Funções clicáveis
case $BUTTON in
    1) bash ~/.dotfiles/.local/bin/dmenu/dmenu-powertop ;;
    6) setsid -f st -e emacs -nw "$0" ;;
esac

# Identifica os dispositivos de bateria e carregador
DEVICE_CARREGADOR=$(ls /sys/class/power_supply/ | grep -m1 "ACAD")
DEVICE_BATERIA=$(ls /sys/class/power_supply/ | grep -m1 "BAT")

# Verifica se o carregador existe e está ligado
if [[ -n "$DEVICE_CARREGADOR" ]] && [[ -e "/sys/class/power_supply/$DEVICE_CARREGADOR/online" ]]; then
    is_plugged=$(cat "/sys/class/power_supply/$DEVICE_CARREGADOR/online")
else
    is_plugged=2 # Valor indicando ausência do carregador
fi

# Verifica se a bateria existe e obtém o nível de carga
if [[ -n "$DEVICE_BATERIA" ]] && [[ -e "/sys/class/power_supply/$DEVICE_BATERIA/capacity" ]]; then
    battery_level=$(cat "/sys/class/power_supply/$DEVICE_BATERIA/capacity")
else
    battery_level=0 # Assume 0% se a bateria não for detectada
fi

# Define o ícone e a cor com base no estado do carregador e nível de bateria
if [[ "$is_plugged" -eq 1 ]]; then
    icon="^c$COLOR_7^"
else
    case $battery_level in
        [0-30])   icon="^c$COLOR_3^" ;; # Bateria crítica
        [31-40])  icon="^c$COLOR_2^" ;; # Bateria baixa
        [41-60])  icon="^c$COLOR_1^" ;; # Bateria moderada
        [61-90])  icon="^c$COLOR_7^" ;; # Bateria boa
        *)        icon="^c$COLOR_8^" ;; # Bateria cheia
    esac
fi

# Apresentacao condicionada
case "$OPERATION_MODE" in
    "MINIMO")
        echo ""
    ;;
    *)
        echo "$icon ^d^$battery_level󰏰  "
    ;;
esac

exit 0
