#!/bin/bash

# Funções clicáveis
case $BUTTON in
    1) bash ~/.dotfiles/.local/bin/dmenu/dmenu-powertop ;;
    6) setsid -f st -e emacs -nw "$0" ;;
esac

# Identifica os dispositivos de bateria e carregador
DEVICE_CARREGADOR=$(ls /sys/class/power_supply/ | grep -m1 "ACAD")
DEVICE_BATERIA=$(ls /sys/class/power_supply/ | grep -m1 "BAT")

# Verifica se o carregador existe e está ligado
if [[ -n "$DEVICE_CARREGADOR" ]] && [[ -e "/sys/class/power_supply/$DEVICE_CARREGADOR/online" ]]; then
    is_plugged=$(cat "/sys/class/power_supply/$DEVICE_CARREGADOR/online")
else
    is_plugged=2 # Valor indicando ausência do carregador
fi

# Verifica se a bateria existe e obtém o nível de carga
if [[ -n "$DEVICE_BATERIA" ]] && [[ -e "/sys/class/power_supply/$DEVICE_BATERIA/capacity" ]]; then
    battery_level=$(cat "/sys/class/power_supply/$DEVICE_BATERIA/capacity")
else
    battery_level=0 # Assume 0% se a bateria não for detectada
fi

# Define o ícone e a cor com base no estado do carregador e nível de bateria
if [[ "$is_plugged" -eq 1 ]]; then
    icon="^c#2aa198^"
else
    case $battery_level in
        [0-30])   icon="^c#dc322f^" ;; # Bateria crítica
        [31-40])  icon="^c#cb4b16^" ;; # Bateria baixa
        [41-60])  icon="^c#b58900^" ;; # Bateria moderada
        [61-90])  icon="^c#2aa198^" ;; # Bateria boa
        *)        icon="^c#859900^" ;; # Bateria cheia
    esac
fi

# Saída formatada
echo "$icon ^d^$battery_level󰏰  "
