#!/bin/bash

# Carrega informacoes do modo de operacao
arquivo_modo="$HOME/.cache/dwmblocks_modo_operacao"

if [ -f $arquivo_modo ]; then
    source $arquivo_modo
else
    OPERATION_MODE="COMPLETO"
fi

# Carrega as cores do tema
source ~/.theme_selected

# Display the current time in HH:MM:SS.
day=$(date "+%d")
image="/usr/share/icons/Numix/64/places/calendar-$day.svg"

clock=$(date '+%I')

case "$clock" in
	"00") icon="🕛" ;;
	"01") icon="🕐" ;;
	"02") icon="🕑" ;;
	"03") icon="🕒" ;;
	"04") icon="🕓" ;;
	"05") icon="🕔" ;;
	"06") icon="🕕" ;;
	"07") icon="🕖" ;;
	"08") icon="🕗" ;;
	"09") icon="🕘" ;;
	"10") icon="🕙" ;;
	"11") icon="🕚" ;;
	"12") icon="🕛" ;;
esac


case $BUTTON in
    1) notify-send "Este Mês" "$(cal | sed "s/\<$(date +'%e'|tr -d ' ')\>/<b><span color='red'>&<\/span><\/b>/")" \
        --icon $image && notify-send "Eventos Agendados" "$(calcurse -d7)" ;;
	2) setsid -f st -e calcurse ;;
	3) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d4\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac


day=$(date "+%d")
#data=$(date +'%d/%m/%Y')
data=$(date +"%a %d %b de %Y" | sed 's/  / /g')
#data=$(date +'%d/%m')
image="/usr/share/icons/Numix/64/places/calendar-$day.svg"



# Apresentacao condicionada
case "$OPERATION_MODE" in
    "MINIMO")
		echo "^c$COLOR_5^ ^d^$data  "
    ;;
	"MEDIO")
		echo "^c$COLOR_5^ ^d^$(date +'%d/%m/%y')  "
	;;
	*)
		echo "^c$COLOR_5^ ^d^$data  "
    ;;
esac
