#!/bin/bash
#
# funcoes cliclaveis
case $BUTTON in
   # 1) bash ~/.dotfiles/.local/bin/dwm/toggle_wifi.sh ;;
    1)
        myip=$(ip -f inet address | grep inet | grep -v 'lo$' | cut -d ' ' -f 6,13 && curl ifconfig.me && echo ' external ip')
        notify-send "Ips atuais" "$myip" --icon "/usr/share/icons/Numix/64/devices/network-modem.svg"
    ;;
    3) bash ~/.dotfiles/.local/bin/dmenu/dmenu-vpn ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac

# Identifica os devices de rede do sistema
DEVICE_WIFI=$(ls /sys/class/net/ | grep "wlp" | awk '{print $1}')
DEVICE_ETHERNET=$(ls /sys/class/net/ | grep "enp" | awk '{print $1}')

# Verifica se o ethernet existe
if [ -e /sys/class/net/$DEVICE_ETHERNET/operstate ]; then

    # Verifica se o ethernet esta ligado
    status_ethernet=$(cat /sys/class/net/$DEVICE_ETHERNET/operstate | grep "up" -ic)
else
    status_ethernet=0
fi

if [ $status_ethernet -eq 1 ]; then
    ip=$(ip addr show $DEVICE_ETHERNET  | grep 'inet' | awk '{print$2}' | sed 's/\/[0-9]*//' | head -1)
    ethernet="^c#6c71c4^󰈀 ^d^$ip  "
else
    ethernet=""
fi

echo "$ethernet"
