#!/bin/bash
# Configuração do PATH
export PATH=/usr/local/bin:/usr/bin:/bin

case $BUTTON in
	1) bash ~/.config/suckless/scripts/dwm/altera-layout-teclado ;;
    3) bash ~/.config/suckless/scripts/dmenu/dmenu-keyboard ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac

layout=$(setxkbmap -query | grep layout | awk '{print$2}' | grep 'br' -ic)
lay=$(setxkbmap -query | grep layout | awk '{print$2}')
layout_atual="^c#268bd2^󰌌 ^d^$lay"

# Verifique o estado atual do Caps Lock
CAPS_STATE=$(xset q | grep "Caps Lock:" | awk '{print $4}')

if [ "$CAPS_STATE" == "on" ]; then
    caps="^c#dc322f^󰪛"
else
    caps=""
fi

# Verificar o estado atual do Num Lock
NUMLOCK_STATE=$(xset q | grep "Num Lock:" | awk '{print $8}')

if [ "$NUMLOCK_STATE" == "on" ]; then
    num="^c#b58900^󰎠"
else
    num=""
fi

# Logica para visualizacao
if [[ ! -z "$caps" ]]; then
   if [[ ! -z "$num" ]]; then
     echo "$layout_atual $caps $num  "
   else
       echo "$layout_atual $caps  "
   fi
else
   if [[ ! -z "$num" ]]; then
      echo "$layout_atual $num  "
   else
       echo "$layout_atual  "
   fi
fi
exit 0
