#!/bin/bash

# Carrega informacoes do modo de operacao
arquivo_modo="$HOME/.cache/dwmblocks_modo_operacao"

if [ -f $arquivo_modo ]; then
    source $arquivo_modo
else
    OPERATION_MODE="COMPLETO"
fi

# Carrega as cores do tema
source ~/.theme_selected

# Configuração do PATH
export PATH=/usr/local/bin:/usr/bin:/bin

# Funções clicáveis
case $BUTTON in
    1) bash ~/.config/suckless/scripts/dwm/dwm-altera-layout-teclado ;;
    3) bash ~/.config/suckless/scripts/dmenu/dmenu-keyboard ;;
    6) setsid -f st -e emacs -nw "$0" ;;
esac

# Captura o layout atual do teclado
lay=$(setxkbmap -query 2>/dev/null | grep layout | awk '{print $2}')
if [[ -z "$lay" ]]; then
    lay="unknown"
fi

layout_atual="^b$COLOR_6^^c$COLOR_BACKGROUND^ 󰌌"

# Verifique o estado atual do Caps Lock
CAPS_STATE=$(xset q 2>/dev/null | grep "Caps Lock:" | awk '{print $4}')
if [[ "$CAPS_STATE" == "on" ]]; then
    caps="󰪛"
else
    caps=""
fi

# Verificar o estado atual do Num Lock
NUMLOCK_STATE=$(xset q 2>/dev/null | grep "Num Lock:" | awk '{print $8}')
if [[ "$NUMLOCK_STATE" == "on" ]]; then
    num="󰎠"
else
    num=""
fi

# Lógica para visualização
output="$layout_atual"
[[ ! -z "$caps" ]] && output="$output $caps"
[[ ! -z "$num" ]] && output="$output $num"


# Apresentacao condicionada
case "$OPERATION_MODE" in
    "MINIMO")
        echo ""
    ;;
    "MEDIO")
        echo ""
    ;;
    *)
        echo "$output ^d^^c$COLOR_BACKGROUND^^b$COLOR_14^ $lay ^d^ "
    ;;
esac

# Garante que o script finalize com sucesso
exit 0
