#!/bin/bash

# Carrega as cores do tema
source ~/.theme_selected

# funcoes cliclaveis
case $BUTTON in
    1) xsetroot -name "fsignal:togglescratch ui 4" ;;
    3) st -n "htop"  -e "htop"  &>/dev/null & ;;
    6) setsid -f st -e emacs -nw "$0" ;;
esac

# Captura a temperatura do CPU (verifica se "sensors" retorna resultado)
tempCpu=$(sensors 2>/dev/null | awk '/edge/ {print $2}' | sed 's/+//')
if [ -z "$tempCpu" ]; then
    tempCpu="" # Substituto caso sensores não estejam disponíveis
fi

# Lê o estado atual do CPU
read cpu a b c previdle rest < /proc/stat
prevtotal=$((a+b+c+previdle))

# Aguarda 0.5 segundos
sleep 0.5

# Lê o estado do CPU novamente
read cpu a b c idle rest < /proc/stat
total=$((a+b+c+idle))

# Calcula o uso do CPU
if [ $((total-prevtotal)) -ne 0 ]; then
    usageCpu=$((100 * ((total-prevtotal) - (idle-previdle)) / (total-prevtotal)))
else
    usageCpu=0
fi

# Define o ícone baseado no uso do CPU
if [ "$usageCpu" -le 10 ]; then
    icon="^c$COLOR_7^ "
elif [ "$usageCpu" -le 40 ]; then
    icon="^c$COLOR_1^ "
elif [ "$usageCpu" -le 60 ]; then
    icon="^c$COLOR_2^ "
elif [ "$usageCpu" -le 100 ]; then
    icon="^c$COLOR_3^ "
else
    icon="^c$COLOR_7^ "
fi

# Exibe o resultado
echo "$icon^d^$usageCpu󰏰 $tempCpu  "
