#!/bin/bash

# Carrega as cores do tema
source ~/.theme_selected

# Display currently playing music.
PLAYERS="--player=mpd,spotify,mpv,vlc,%any"

# Icones
icon="^c$COLOR_8^󰝚"
paused_icon="^c$COLOR_1^"

# Verifica status
if status="$(playerctl $PLAYERS status 2>&1)" && [ "$status" != "Stopped" ]; then
    [ "$status" = "Paused" ] && icon="$paused_icon"

    #song="$(playerctl $PLAYERS metadata --format="{{title}} - {{artist}}")"
    song="$(playerctl $PLAYERS metadata --format="{{title}}")"
fi

[ -z "$song" ] && exit
echo "$icon ^d^$song  "
