#!/bin/bash

# Carrega as cores do tema
source ~/.theme_selected

# funcoes cliclaveis
case $BUTTON in
    1) xsetroot -name "fsignal:togglescratch ui 4" ;;
    3) st -n "htop"  -e "htop"  &>/dev/null & ;;
    6) setsid -f st -e emacs -nw "$0" ;;
esac

# Display RAM usage.
memory=$(free | grep Mem | awk '{printf "%.0f\n", $3/$2 * 100.0}')

echo "^c$COLOR_7^ ^d^$memory󰏰  "
