#!/bin/bash

# funcoes cliclaveis
case $BUTTON in
	1) bash ~/.dotfiles/.local/bin/dwm/muta_microfone ;;
    2) bash ~/.dotfiles/.local/bin/dmenu/dmenu-controle-som ;;
    #3) setsid -f st -e pulsemixer ;;
    3) xsetroot -name "fsignal:togglescratch ui 3" ;;
    4) bash ~/.dotfiles/.local/bin/dwm/aumenta_volume_microfone ;;
    5) bash ~/.dotfiles/.local/bin/dwm/diminui_volume_microfone ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac

# Lê o nome da distribuição a partir do arquivo /etc/os-release
if [ -f /etc/os-release ]; then
    . /etc/os-release
    case "$ID" in
        arch)
            MICROFONE="pcm0c"
            ;;

        debian)
            MICROFONE="pcm3p"
            ;;
        *)
            echo "Sistema desconhecido ou não suportado: $ID"
            ;;
    esac
else
    echo "Não foi possível determinar a distribuição. O arquivo /etc/os-release não existe."
fi

# Display an icon if the microphone is muted.
#microfoneOn=$(cat /proc/asound/card0/$MICROFONE/sub0/status | grep "RUNNING")
microfone=$(pactl get-source-volume @DEFAULT_SOURCE@ | grep "Volume" | awk '{print$5}' | sed 's/%//')
muteMic=$(pactl get-source-mute @DEFAULT_SOURCE@ | grep -E 'sim|yes' -ic)

if [ "$muteMic" -eq 1 ]; then
    iconMic="^c#4A5947^ $microfone󰏰"
else
    iconMic="^c#d33682^ ^d^$microfone󰏰"
fi

echo "$iconMic  "
