#!/bin/bash

# Carrega informacoes do modo de operacao
arquivo_modo="$HOME/.cache/dwmblocks_modo_operacao"

if [ -f $arquivo_modo ]; then
    source $arquivo_modo
else
    OPERATION_MODE="COMPLETO"
fi

# Carrega as cores do tema
source ~/.theme_selected
# Lê o nome da distribuição a partir do arquivo /etc/os-release
if [ -f /etc/os-release ]; then
    . /etc/os-release
    case "$ID" in
        arch)
            MICROFONE="pcm0c"
            ;;

        debian)
            MICROFONE="pcm3p"
            ;;
        *)
            echo "Sistema desconhecido ou não suportado: $ID"
            ;;
    esac
else
    echo "Não foi possível determinar a distribuição. O arquivo /etc/os-release não existe."
fi

# funcoes cliclaveis
case $BUTTON in
	1) bash ~/.config/suckless/scripts/dwm/dwm-muta-microfone ;;
    2) bash ~/.config/suckless/scripts/dmenu/dmenu-controle-som ;;
    3) xsetroot -name "fsignal:togglescratch ui 3" ;;
    4) bash ~/.config/suckless/scripts/dwm/dwm-aumenta-volume-microfone ;;
    5) bash ~/.config/suckless/scripts/dwm/dwm-diminui-volume-microfone ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac

# Display an icon if the microphone is muted.
#microfoneOn=$(cat /proc/asound/card0/$MICROFONE/sub0/status | grep "RUNNING")
microfone=$(pactl get-source-volume @DEFAULT_SOURCE@ | grep "Volume" | awk '{print$5}' | sed 's/%//')
muteMic=$(pactl get-source-mute @DEFAULT_SOURCE@ | grep -E 'sim|yes' -ic)

if [ "$muteMic" -eq 1 ]; then
    iconMic="^b#4A5947^^c$COLOR_BACKGROUND^  ^d^"
else
    iconMic="^b$COLOR_4^^c$COLOR_BACKGROUND^  ^d^^c$COLOR_BACKGROUND^^b$COLOR_12^ $microfone ^d^"
fi

# Apresentacao condicionada
case "$OPERATION_MODE" in
    "MINIMO")
        echo ""
    ;;
    "MEDIO")
        echo ""
    ;;
    *)
        echo "$iconMic "
    ;;
esac

exit 0;
