#!/bin/bash

# Carrega função para aplicar o tema e o tema de cores
source ~/.config/suckless/scripts/dwmblocks/sb-carrega-tema-dwmblocks

# Display volume levels.
case $BUTTON in
	1) bash ~/.config/suckless/scripts/dwm/dwm-muta-volume ;;
    2) bash ~/.config/suckless/scripts/dmenu/dmenu-controle-som ;;
    #3) setsid -f st -e pulsemixer ;;
    3) xsetroot -name "fsignal:togglescratch ui 3" ;;
    4) bash ~/.config/suckless/scripts/dwm/dwm-aumenta-volume ;;
    5) bash ~/.config/suckless/scripts/dwm/dwm-diminui-volume ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac


device=$(pactl get-default-sink)
muteVol=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -E 'sim|yes' -ic)
volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep "Volume" | awk '{print$5}' | sed 's/%//')

cor_forte="$COLOR_6"
cor_fraca="$COLOR_14"

case "$device" in
    *pci*analog*)      device="I" ;;   # placa on-board
    *usb*Headset*)     device="F" ;;   # fone USB
    *pci*hdmi*)        device="H" ;;   # qualquer outro USB
    *)                 device="?" ;;
esac


if [ "$muteVol" -eq 1 ]; then
    iconVolume="󰸈"
    cor_forte="#4A5947"
    cor_fraca="#4A5947"

else
    if [ "$volume" -le 30 ]; then
        iconVolume="󰕿"
    elif [ "$volume" -le 60 ]; then
        iconVolume="󰖀"
    elif [ "$volume" -ge 61 ]; then
        iconVolume="󰕾"
    fi
fi
output=$(aplicar_tema "$iconVolume" "$volume $device" "$cor_forte" "$cor_fraca")

# Apresentacao condicionada
case "$OPERATION_MODE" in
    "MINIMO")
        echo ""
    ;;
    "MEDIO")
        echo ""
    ;;
    *)
        echo "$output"
    ;;
esac

exit 0
