#!/bin/bash

# Configurações do script
API_KEY="8b05d62206f459e1d298cbe5844d7d87"
CITY="São%20José%20dos%20Pinhais,%20BR"
UNITS="metric"  # Use 'imperial' para Fahrenheit
LANG="pt_br"    # Idioma da descrição do tempo

# Substitui espaços por %20 na cidade
CITY_ENCODED=$(echo "$CITY" | sed 's/ /%20/g')

# Monta a URL da API
URL="http://api.openweathermap.org/data/2.5/weather?q=${CITY_ENCODED}&appid=${API_KEY}&units=${UNITS}&lang=${LANG}"

# Requisição e processamento
WEATHER=$(curl -sf "$URL")

# Separa a informacao recebida em variaveis
WEATHER_DESC=$(echo "$WEATHER" | jq -r ".weather[0].description")
WEATHER_TEMP=$(echo "$WEATHER" | jq ".main.temp" | cut -d "." -f 1)
WEATHER_ICON_CODE=$(echo "$WEATHER" | jq -r ".weather[].icon" | head -1)
WEATHER_FEELS_LIKE=$(echo "$WEATHER" | jq ".main.feels_like" | cut -d "." -f 1)
WEATHER_ICON=""

case $WEATHER_ICON_CODE in
    "01d")
        WEATHER_ICON=""
        WEATHER_HEX="#ffd86b"
        ;;
    "01n")
        WEATHER_ICON=""
        WEATHER_HEX="#fcdcf6"
        ;;
    "02d")
        WEATHER_ICON=""
        WEATHER_HEX="#adadff"
        ;;
    "02n")
        WEATHER_ICON=""
        WEATHER_HEX="#adadff"
        ;;
    "03d")
        WEATHER_ICON=""
        WEATHER_HEX="#adadff"
        ;;
    "03n")
        WEATHER_ICON=""
        WEATHER_HEX="#adadff"
        ;;
    "04d")
        WEATHER_ICON=""
        WEATHER_HEX="#adadff"
        ;;
    "04n")
        WEATHER_ICON=""
        WEATHER_HEX="#acb0d0"
        ;;
    "09d")
        WEATHER_ICON=""
        WEATHER_HEX="#6b95ff"
        ;;
    "09n")
        WEATHER_ICON=""
        WEATHER_HEX="#6b95ff"
        ;;
    "10d")
        WEATHER_ICON=""
        WEATHER_HEX="#6b95ff"
        ;;
    "10n")
        WEATHER_ICON=""
        WEATHER_HEX="#6b95ff"
        ;;
    "11d")
        WEATHER_ICON=""
        WEATHER_HEX="#ffeb57"
        ;;
    "11n")
        WEATHER_ICON=""
        WEATHER_HEX="#ffeb57"
        ;;
    "13d")
        WEATHER_ICON=""
        WEATHER_HEX="#e3e6fc"
        ;;
    "13n")
        WEATHER_ICON=""
        WEATHER_HEX="#e3e6fc"
        ;;
    "40d")
        WEATHER_ICON=""
        WEATHER_HEX="#84afdb"
        ;;
    "40n")
        WEATHER_ICON=""
        WEATHER_HEX="#84afdb"
        ;;
    *)
        WEATHER_ICON=""
        WEATHER_HEX="#adadff"
        ;;
esac

if [ "$WEATHER" != "" ]; then
    echo "^c$WEATHER_HEX^$WEATHER_ICON^d^ $WEATHER_TEMP°C $WEATHER_DESC  "
else
    echo "Erro ao obter clima"
fi
