# Theme: xresources
# Updated from .Xresources on ter 07 jul 2026 20:39:29 -03

[urgency_low]
    background = "#002b36"
    foreground = "#dc322f"
    frame_color = "#dc322f"

[urgency_normal]
    background = "#002b36"
    foreground = "#839496"
    frame_color = "#cb4b16"

[urgency_critical]
    background = "#002b36"
    foreground = "#6c71c4"
    frame_color = "#6c71c4"
