# Theme: xresources
# Updated from .Xresources on qua 08 jul 2026 17:43:46 -03

[urgency_low]
    background = "#1a1a2e"
    foreground = "#ff6c6c"
    frame_color = "#ff6c6c"

[urgency_normal]
    background = "#1a1a2e"
    foreground = "#e0e0e0"
    frame_color = "#9c64e8"

[urgency_critical]
    background = "#1a1a2e"
    foreground = "#7ec8ff"
    frame_color = "#7ec8ff"
