# Theme: xresources
# Updated from .Xresources on seg 06 jul 2026 21:13:02 -03

[urgency_low]
    background = "#303446"
    foreground = "#ca9ee6"
    frame_color = "#ca9ee6"

[urgency_normal]
    background = "#303446"
    foreground = "#c6d0f5"
    frame_color = "#ef9f76"

[urgency_critical]
    background = "#303446"
    foreground = "#e5c890"
    frame_color = "#e5c890"
