#!/bin/bash

# Configuration options
wallpaper_dir="$HOME/.wallpapers"

# Check if filename argument is provided
if [ $# -eq 0 ]; then
    # Select a random file from the wallpaper directory
    filename="$(find $wallpaper_dir/ -type f \( -iname \*.jpg -o -iname \*.png -o -iname \*.jpeg -o -iname \*.gif \) | shuf -n 1)"
else
    # Use the provided argument as the filename
    filename="$1"
fi

notify-send "Generating Scheme"

# Gera o scheme das cores
wal -i "$filename"

# Carrega os valores das cores
pywal_color0="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color0')"
pywal_color1="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color1')"
pywal_color2="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color2')"
pywal_color3="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color3')"
pywal_color4="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color4')"
pywal_color5="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color5')"
pywal_color6="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color6')"
pywal_color7="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color7')"
pywal_color8="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color8')"
pywal_color9="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color9')"
pywal_color10="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color10')"
pywal_color11="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color11')"
pywal_color12="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color12')"
pywal_color13="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color13')"
pywal_color14="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color14')"
pywal_color15="$(cat ~/.cache/wal/colors.json | jq -r '.colors.color15')"

# Salva a configuracao para o DWM
rm -rf $HOME/.config/suckless/dwm/themes/pywal_dark.h
cat > $HOME/.config/suckless/dwm/themes/pywal_dark.h << EOF
static char normfgcolor[]                = "${pywal_color7}";
static char normbgcolor[]                = "${pywal_color0}";
static char normbordercolor[]            = "${pywal_color0}";
static char normfloatcolor[]             = "${pywal_color0}";

static char selfgcolor[]                 = "${pywal_color7}";
static char selbgcolor[]                 = "${pywal_color2}";
static char selbordercolor[]             = "${pywal_color7}";
static char selfloatcolor[]              = "${pywal_color2}";

static char titlenormfgcolor[]           = "${pywal_color7}";
static char titlenormbgcolor[]           = "${pywal_color0}";
static char titlenormbordercolor[]       = "${pywal_color0}";
static char titlenormfloatcolor[]        = "${pywal_color2}";

static char titleselfgcolor[]            = "${pywal_color0}";
static char titleselbgcolor[]            = "${pywal_color2}";
static char titleselbordercolor[]        = "${pywal_color2}";
static char titleselfloatcolor[]         = "${pywal_color2}";

static char tagsnormfgcolor[]            = "${pywal_color7}";
static char tagsnormbgcolor[]            = "${pywal_color0}";
static char tagsnormbordercolor[]        = "${pywal_color0}";
static char tagsnormfloatcolor[]         = "${pywal_color2}";

static char tagsselfgcolor[]             = "${pywal_color0}";
static char tagsselbgcolor[]             = "${pywal_color2}";
static char tagsselbordercolor[]         = "${pywal_color2}";
static char tagsselfloatcolor[]          = "${pywal_color2}";

static char hidnormfgcolor[]             = "${pywal_color13}";
static char hidselfgcolor[]              = "${pywal_color14}";
static char hidnormbgcolor[]             = "${pywal_color0}";
static char hidselbgcolor[]              = "${pywal_color0}";

static char urgfgcolor[]                 = "${pywal_color0}";
static char urgbgcolor[]                 = "${pywal_color15}";
static char urgbordercolor[]             = "${pywal_color3}";
static char urgfloatcolor[]              = "${pywal_color2}";

static char c000000[]                    = "${c000000}";
EOF

# Salva a configuracao para o dmenu
rm -rf $HOME/.config/suckless/dmenu/themes/pywal_dark.h
cat > $HOME/.config/suckless/dmenu/themes/pywal_dark.h << EOF
static const char *colors[SchemeLast][2] = {
/*                            fg         bg       */
[SchemeNorm]          = { "${pywal_color7}", "${pywal_color0}" }, // Fonte normal, fundo normal
[SchemeSel]           = { "${pywal_color7}", "${pywal_color2}" }, // Fonte selecionada, fundo selecionado
[SchemeBorder]        = { "${pywal_color0}", "${pywal_color7}" }, // Borda normal, borda selecionada
[SchemeSelHighlight]  = { "${pywal_color0}", "${pywal_color2}" }, // Destaque de seleção
[SchemeNormHighlight] = { "${pywal_color7}", "${pywal_color0}" }, // Destaque normal
[SchemeOut]           = { "${pywal_color7}", "${pywal_color6}" }, // Destaque de saída
};
EOF

# Salva a configuracao para o slock
rm -rf cat > $HOME/.config/suckless/slock/themes/pywal_dark.h
cat > $HOME/.config/suckless/slock/themes/pywal_dark.h << EOF
static const char *colorname[NUMCOLS] = {
	[INIT] =   "${pywal_color0}",   /* after initialization */
	[INPUT] =  "${pywal_color7}",   /* during input */
	[FAILED] = "${pywal_color9}",   /* wrong password */
	[CAPS] =   "${pywal_color8}",   /* CapsLock on */
	[BLOCKS] = "${pywal_color3}",   /* key feedback block */
};
EOF

# Salva a configuracao para o slock
rm -rf $HOME/.config/suckless/st/themes/pywal_dark.h
cp $HOME/.cache/wal/colors-wal-st.h $HOME/.config/suckless/st/themes/pywal_dark.h

# Salva cores para o rofi
# Substitui cores básicas
sed -i "s/^\([[:space:]]*bg0[[:space:]]*:[[:space:]]*\)#[0-9a-fA-F]\{6\}\(;\)/\1$pywal_color0\2/" $HOME/.config/rofi/themes/pywal_dark.rasi
sed -i "s/^\([[:space:]]*bg1[[:space:]]*:[[:space:]]*\)#[0-9a-fA-F]\{6\}\(;\)/\1$pywal_color0\2/" $HOME/.config/rofi/themes/pywal_dark.rasi
sed -i "s/^\([[:space:]]*grey0[[:space:]]*:[[:space:]]*\)#[0-9a-fA-F]\{6\}\(;\)/\1$pywal_color8\2/" $HOME/.config/rofi/themes/pywal_dark.rasi
sed -i "s/^\([[:space:]]*fg0[[:space:]]*:[[:space:]]*\)#[0-9a-fA-F]\{6\}\(;\)/\1$pywal_color7\2/" $HOME/.config/rofi/themes/pywal_dark.rasi

# Substitui cores acentuadas
sed -i "s/^\([[:space:]]*blue[[:space:]]*:[[:space:]]*\)#[0-9a-fA-F]\{6\}\(;\)/\1$pywal_color1\2/" $HOME/.config/rofi/themes/pywal_dark.rasi
sed -i "s/^\([[:space:]]*red[[:space:]]*:[[:space:]]*\)#[0-9a-fA-F]\{6\}\(;\)/\1$pywal_color2\2/" $HOME/.config/rofi/themes/pywal_dark.rasi
sed -i "s/^\([[:space:]]*orange[[:space:]]*:[[:space:]]*\)#[0-9a-fA-F]\{6\}\(;\)/\1$pywal_color3\2/" $HOME/.config/rofi/themes/pywal_dark.rasi
sed -i "s/^\([[:space:]]*green[[:space:]]*:[[:space:]]*\)#[0-9a-fA-F]\{6\}\(;\)/\1$pywal_color4\2/" $HOME/.config/rofi/themes/pywal_dark.rasi

# Substitui cor específica do statusline
sed -i "s/^\([[:space:]]*bgStatusline3[[:space:]]*:[[:space:]]*\)#[0-9a-fA-F]\{6\}\(;\)/\1$pywal_color8\2/" $HOME/.config/rofi/themes/pywal_dark.rasi

# Salva a configuracao para o dunst
sed -i "s/^[[:space:]]*\(frame_color[[:space:]]*=[[:space:]]*\"\).*\(\"\)/\1$pywal_color7\2/" ~/.config/dunst/themes/Pywal_Dark
sed -i "s/^[[:space:]]*\(background[[:space:]]*=[[:space:]]*\"\).*\(\"\)/\1$pywal_color0\2/" ~/.config/dunst/themes/Pywal_Dark
sed -i "s/^[[:space:]]*\(foreground[[:space:]]*=[[:space:]]*\"\).*\(\"\)/\1$pywal_color7\2/" ~/.config/dunst/themes/Pywal_Dark
