#!/bin/bash
source ~/.theme_selected

# Display an indicator during screen records.
camera=$(lsmod | grep "uvcvideo" | awk '{print$3}' | head -1)
PID_FILE="/tmp/rec_pid"

# Inicia a variavel de retorno
iconCam=""
iconRec=""

if [ "$camera" = "1" ]; then
	iconCam="^c#dc322f^^d^"
else
    iconCam=""
fi

# Verificar se há gravação em andamento
if [ -f $PID_FILE ] && [ -s $PID_FILE ]; then
 	iconRec="^c$COLOR_3^󰑊^d^"
else
    iconRec=""
fi

# Mostra o icone conforme a necessidade
if [ ! -z $iconCam ] && [ ! -z $iconRec ]; then
    echo "$iconCam $iconRec  "
    exit 0
fi

if [ ! -z $iconCam ]; then
    echo "$iconCam  "
    exit 0
fi

if [ ! -z $iconRec ]; then
    echo "$iconRec  "
    exit 0
fi

echo ""
exit 0
