#!/bin/bash

MINIMO="Minimo - Apenas data, Hora e Pomodoro"
COMPLETO="Completo - Todos os Blocks possíveis"
MEDIO="Médio - Apenas data, hora, volumes, players e pomodoro"

# Variable passed to dmenu
options="$COMPLETO\n$MEDIO\n$MINIMO"

chosen="$(echo -e "$options" | dmenu -p "Modos DWMBLOCKS " )"
case $chosen in
    $MINIMO)
        MODO_SELECIONADO="MINIMO"
    ;;
    $MEDIO)
        MODO_SELECIONADO="MEDIO"
    ;;
    $COMPLETO)
        MODO_SELECIONADO="COMPLETO"
    ;;
esac

if [[ -z $chosen ]]; then
    exit 0
else

    rm -rf $HOME/.cache/dwmblocks_modo_operacao
    cat > $HOME/.cache/dwmblocks_modo_operacao << EOF
#!/bin/bash
OPERATION_MODE="$MODO_SELECIONADO"
EOF
    for i in {35..51}; do
        kill -$i $(pidof dwmblocks)
    done
    notify-send -t 3000 "Modo DWMBlocks" "Alterado o modo do DWMBlocks para $MODO_SELECIONADO" --icon="/usr/share/icons/ePapirus/16x16/actions/escape-direction-all.svg"
fi
