#!/bin/bash

shutdown=" Shutdown"
reboot=" Reboot"
logout=" Logout"
suspend="󰒲 Suspend"
#hibernate="Hibernate"

# Variable passed to rofi
options="$shutdown\n$reboot\n$logout\n$suspend"

chosen="$(echo -e "$options" | dmenu -p "Power-Menu " )"
case $chosen in
    $shutdown)
	systemctl poweroff
	;;
    $reboot)
    systemctl reboot
	;;
    $logout)
    sudo -A pkill -KILL -u $USER
	;;
    $suspend)
	systemctl suspend
	;;
    $hibernate)
	systemctl hibernate
	;;
esac
