#!/bin/bash

# Lê o nome da distribuição a partir do arquivo /etc/os-release
if [ -f /etc/os-release ]; then
    . /etc/os-release
    case "$ID" in
        arch)
            sudo_askpass="/usr/lib/ssh/gnome-ssh-askpass3"
            ;;
        debian)
            sudo_askpass="/usr/bin/ssh-askpass"
            ;;
        *)
            echo "Sistema desconhecido ou não suportado: $ID"
            ;;
    esac
else
    echo "Não foi possível determinar a distribuição. O arquivo /etc/os-release não existe."
fi


status=$(envycontrol --query)

integrated="Integrated - Apenas AMD"
hybrid="Hybrid - AMD + Nvidia"
nvidia="Nvidia - Apenas Nvidia"

# Variable passed to dmenu
options="$hybrid\n$integrated\n$nvidia"

chosen="$(echo -e "$options" | dmenu -p "Controle Modo Operação Nvidia - Atual é: $status" )"
case $chosen in
    $hybrid)
	    SUDO_ASKPASS="$sudo_askpass" sudo envycontrol --switch hybrid --force

	    notify-send -t 3000 "EnvyControl Change" "Alterado modo de operação para Hybrid" --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"

        # Definir o tempo de espera entre as notificações
        for i in {3..1}; do
            notify-send -t 1000 "EnvyControl Change" "Sistema será reiniciado em $i" --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"
            sleep 1
        done

        # Notificação final antes do reinício
        notify-send -t 1000 "EnvyControl Change" "Reiniciando o sistema..." --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"

        # Reiniciar o sistema
        SUDO_ASKPASS="$sudo_askpass" sudo shutdown -r now
    ;;
    $integrated)
	    SUDO_ASKPASS="$sudo_askpass" sudo envycontrol -s integrated
	    notify-send -t 3000 "EnvyControl Change" "Alterado modo de operação para Integrated" --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"

        # Definir o tempo de espera entre as notificações
        for i in {3..1}; do
            notify-send -t 1000 "EnvyControl Change" "Sistema será reiniciado em $i" --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"
            sleep 1
        done

        # Notificação final antes do reinício
        notify-send -t 1000 "EnvyControl Change" "Reiniciando o sistema..." --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"

        # Reiniciar o sistema
        SUDO_ASKPASS="$sudo_askpass" sudo shutdown -r now
    ;;
    $nvidia)
	    SUDO_ASKPASS="$sudo_askpass" sudo envycontrol -s nvidia
	    notify-send -t 3000 "EnvyControl Change" "Alterado modo de operação para Nvidia" --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"

        # Definir o tempo de espera entre as notificações
        for i in {3..1}; do
            notify-send -t 1000 "EnvyControl Change" "Sistema será reiniciado em $i" --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"
            sleep 1
        done

        # Notificação final antes do reinício
        notify-send -t 1000 "EnvyControl Change" "Reiniciando o sistema..." --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"

        # Reiniciar o sistema
        SUDO_ASKPASS="$sudo_askpass" sudo shutdown -r now
    ;;

esac
