#!/bin/bash

casa_ligar="Casa Ligar"
casa_desligar="Casa Desligar"
ligar_home_lab="HomeLab Ligar"

nordvpn_ligar="Nord VPN Ligar"
nordvpn_desligar="Nord VPN Desligar"

universidade_ligar="Universidade Ligar"
universidade_desligar="Universidade Desligar"

tailscale_up="Tailscale Ligar"
tailscale_down="Tailscale Desligar"

# Variable passed to dmenu
options="$casa_ligar\n$casa_desligar\n$tailscale_up\n$tailscale_down\n$nordvpn_ligar\n$nordvpn_desligar\n$universidade_ligar\n$universidade_desligar\n$ligar_home_lab"

chosen="$(echo -e "$options" | dmenu -p "Liga e desliga VPN " )"
case $chosen in
    $casa_ligar)
         SUDO_ASKPASS=/usr/lib/ssh/gnome-ssh-askpass3 sudo wg-quick up wg0
         notify-send -t 3000 "VPN" "VPN Ligada" --icon="/usr/share/icons/ePapirus/16x16/devices/network-vpn.svg"
         kill -46 $(pidof dwmblocks)
    ;;
    $casa_desligar)
         SUDO_ASKPASS=/usr/lib/ssh/gnome-ssh-askpass3 sudo wg-quick down wg0
         notify-send -t 3000 "VPN" "VPN Desligada" --icon="/usr/share/icons/ePapirus/16x16/devices/network-vpn.svg"
         kill -46 $(pidof dwmblocks)
    ;;
    $tailscale_up)
         SUDO_ASKPASS=/usr/lib/ssh/gnome-ssh-askpass3 sudo tailscale up
         notify-send -t 3000 "VPN Tailscale" "VPN Tailscale Ligada" --icon="/usr/share/icons/ePapirus/16x16/devices/network-vpn.svg"
         kill -46 $(pidof dwmblocks)
         x-www-browser "umbrel.tail65e7c9.ts.net"
         ;;
    $tailscale_down)
         SUDO_ASKPASS=/usr/lib/ssh/gnome-ssh-askpass3 sudo tailscale down
         notify-send -t 3000 "VPN Tailscale" "VPN Tailscale Desligada" --icon="/usr/share/icons/ePapirus/16x16/devices/network-vpn.svg"
         kill -46 $(pidof dwmblocks)
    ;;
    $nordvpn_ligar)
         nordvpn c
         notify-send -t 3000 "NORDVPN" "VPN Ligada" --icon="/usr/share/icons/ePapirus/16x16/devices/network-vpn.svg"
         kill -46 $(pidof dwmblocks)
    ;;
    $nordvpn_desligar)
         nordvpn d
         notify-send -t 3000 "NORDVPN" "VPN Desligada" --icon="/usr/share/icons/ePapirus/16x16/devices/network-vpn.svg"
         kill -46 $(pidof dwmblocks)
    ;;
    $universidade_ligar)
         SUDO_ASKPASS=/usr/lib/ssh/gnome-ssh-askpass3 sudo wg-quick up wg1
         notify-send -t 3000 "VPN" "VPN Ligada" --icon="/usr/share/icons/ePapirus/16x16/devices/network-vpn.svg"
         kill -46 $(pidof dwmblocks)
    ;;
    $universidade_desligar)
         SUDO_ASKPASS=/usr/lib/ssh/gnome-ssh-askpass3 sudo wg-quick down wg1
         notify-send -t 3000 "VPN" "VPN Desligada" --icon="/usr/share/icons/ePapirus/16x16/devices/network-vpn.svg"
         kill -46 $(pidof dwmblocks)
    ;;
    $ligar_home_lab)
         ssh umbrel@192.168.42.152 "/usr/local/bin/wake.sh"
       #  wakeonlan 40:8d:5c:4b:61:7a
         notify-send -t 3000 "Wake-on-Lan Home Lab" "Enviado sinal para ligar servidor"
    ;;
esac
