#!/bin/bash

# Carrega as configuracoes de tema
source $HOME/.dotfiles/.theme_selected

# Identifica os monitores do equipamento
HDMI_DEVICE=$(xrandr -q | grep "HDMI" | awk '{print $1}')
EDP_DEVICE=$(xrandr -q | grep "eDP" | awk '{print $1}')
VIRTUAL_DEVICE=$(xrandr -q | grep "Virtual" | awk '{print $1}')

RES_HDMI=$( xrandr -q | grep "$HDMI_DEVICE" | awk '{print$3}')
RES_EDP=$( xrandr -q | grep "$EDP_DEVICE" | awk '{print$4}')
RES_VIRT=$( xrandr -q | grep "$VIRTUAL_DEVICE" | awk '{print$4}')

# Opcoes
casa="󰍹 Monitor Externo ($RES_HDMI)"
notebook=" Notebook ($RES_EDP)"
modo_game=" Modo Game"
apresentacao="󰐯 Modo Apresentação"
so_monitor_externo="󱧑 Só monitor externo ($RES_HDMI)"
duplica="󰍺 Duplica a mesma visualização ($RES_EDP = $RES_HDMI)"
noite="󱩍 Noite"
dia="󰛨 Dia"
tabletwaconhdmi="󰓶 Tablet Wacon HDMI"
tabletwaconnotebook="󰓶 Tablet Wacon Notebook"

# Variable passed to dmenu
options="$casa\n$notebook\n$modo_game\n$apresentacao\n$so_monitor_externo\n$duplica\n$dia\n$noite\n$tabletwaconhdmi\n$tabletwaconnotebook"

# Escolha do usuario
chosen="$(echo -e "$options" | dmenu -p "Scripts de monitor " )"

# Aplica a escolha
case $chosen in
    $casa)
	    xrandr --output $HDMI_DEVICE --auto --rotate normal --dpi 96 --output $EDP_DEVICE --primary --auto --rotate normal --dpi 96 --left-of $HDMI_DEVICE
	    notify-send -t 3000 "󰡁 HDMI Inserido" "Adicionado tela via HDMI" --icon="/usr/share/icons/ePapirus/16x16/devices/computer.svg"
        bash ~/.fehbg

        rm -f ~/.monitor_config.sh # Remove arquivo temporario
	;;

    $notebook)
	    xrandr --output $HDMI_DEVICE --off --output $EDP_DEVICE --primary --auto --rotate normal --dpi 96
	    notify-send -t 3000 "  Modo Laptop" "Alterado tela para modo Laptop" --icon="/usr/share/icons/ePapirus/16x16/devices/computer-laptop.svg"
        bash ~/.fehbg

        rm -f ~/.monitor_config.sh # Remove arquivo temporario
        cat > ~/.monitor_config.sh << EOF
#!/bin/bash
xrandr --output $HDMI_DEVICE --off --output $EDP_DEVICE --primary --auto --rotate normal --dpi 96
EOF
    ;;

    $modo_game)
        xrandr --output $HDMI_DEVICE --mode 1920x1080 --rate 120 --pos 1920x0 --rotate normal --output $EDP_DEVICE --primary --mode 1920x1080 --rate 144 --pos 0x0 --rotate normal
        systemctl --user stop redshift.service
        killall redshift
        redshift -P -O 6500
        notify-send -t 3000 "󰡁 HDMI Inserido" "Adicionado tela via HDMI" --icon="/usr/share/icons/ePapirus/16x16/devices/computer.svg"
        bash ~/.fehbg

        rm -f ~/.monitor_config.sh # Remove arquivo temporario
        cat > ~/.monitor_config.sh << EOF
#!/bin/bash
xrandr --output $HDMI_DEVICE --mode 1920x1080 --rate 120 --pos 1920x0 --rotate normal --output $EDP_DEVICE --primary --mode 1920x1080 --rate 144 --pos 0x0 --rotate normal
EOF
    ;;

    $so_monitor_externo)
	    xrandr --output $HDMI_DEVICE --primary --auto --rotate normal --dpi 96 --output $EDP_DEVICE --off
	    notify-send -t 3000 "󰡁 Só monitor externo" "Só monitor Externo" --icon="/usr/share/icons/ePapirus/16x16/devices/computer.svg"
        bash ~/.fehbg

        rm -f ~/.monitor_config.sh # Remove arquivo temporario
        cat > ~/.monitor_config.sh << EOF
#!/bin/bash
xrandr --output $HDMI_DEVICE --primary --auto --rotate normal --dpi 96 --output $EDP_DEVICE --off
EOF
    ;;

    $apresentacao)
        killall xautolock;
        notify-send -t 3000 "Encerrado Xautolock" "" --icon="/usr/share/icons/ePapirus/16x16/devices/computer.svg"
    ;;
    $duplica)

        xrandr --output $HDMI_DEVICE --primary --auto --rotate normal --output $EDP_DEVICE --same-as $HDMI_DEVICE
        notify-send -t 3000 "󰡁 Duplica visualização" "Ambos monitores estão com a mesma visualização" --icon="/usr/share/icons/ePapirus/16x16/devices/computer.svg"
        bash ~/.fehbg

        rm -f ~/.monitor_config.sh # Remove arquivo temporario
        cat > ~/.monitor_config.sh << EOF
#!/bin/bash
xrandr --output $HDMI_DEVICE --primary --auto --rotate normal --dpi 96 --output $EDP_DEVICE --same-as $HDMI_DEVICE
EOF
	;;

    $dia)
	    redshift -P -O 6500
	    notify-send -t 3000 "󰛨 Modo Diurno" "Alterado o brilho da tela para o modo diurno" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
	;;

    $noite)
	    redshift -P -O 4500
	    notify-send -t 3000 "󱩍 Modo noturno" "Alterado o brilho da tela para o modo noturno" --icon="/usr/share/icons/ePapirus/16x16/actions/redeyes.svg"
	;;

    $tabletwaconhdmi)
	    /home/anderson/.local/bin/mapwacon.sh -d "Wacom Intuos S Pen stylus" -s "$HDMI_DEVICE"
	    notify-send -t 3000 "󰓶 Tablet Wacon HDMI" "Configurado a área do tablet wacon para a tela HDMI" --icon="/usr/share/icons/ePapirus/16x16/devices/input-tablet.svg"
	;;

    $tabletwaconnotebook)
	    /home/anderson/.local/bin/mapwacon.sh -d "Wacom Intuos S Pen stylus" -s "$EDP_DEVICE"
	    notify-send -t 3000 "󰓶 Tablet Wacon Notebook" "Configurado a área do tablet wacon para a tela do Notebook" --icon="/usr/share/icons/ePapirus/16x16/devices/input-tablet.svg"
	;;
esac
