#!/bin/bash

# Lê o nome da distribuição a partir do arquivo /etc/os-release
if [ -f /etc/os-release ]; then
    . /etc/os-release
    case "$ID" in
        arch)
            sudo_askpass="/usr/lib/ssh/gnome-ssh-askpass3"
            ;;
        debian)
            sudo_askpass="/usr/bin/ssh-askpass"
            ;;
        *)
            echo "Sistema desconhecido ou não suportado: $ID"
            ;;
    esac
else
    echo "Não foi possível determinar a distribuição. O arquivo /etc/os-release não existe."
fi


dwm_pywal="  Mudar para Dwm com Pywal"
dwm_normal="  Mudar para Dwm Normal"
pywal_aleatorio="  Aleatório"
pywal_wal_atual="  Wallpaper Atual"
solarized_dark="  Solarized Dark"
solarized_light="  Solarized Light"
gruvbox_dark="  Gruvbox Dark"
gruvbox_light="  Gruvbox Light"
catppuccin_dark="  Catppuccin Dark"
catppuccin_light="  Catppuccin Light"
nordic_dark="  Nord Dark"
nordic_light="  Nord Light"
dracula_dark="  Dracula Dark"
dracula_light="  Dracula Light"
vaporwave_dark="  Vaporwave Dark"
vaporwave_light="  Vaporwave Light"

# Variable passed to dmenu
options="Dark :\n$catppuccin_dark\n$dracula_dark\n$gruvbox_dark\n$nordic_dark\n$solarized_dark\n$vaporwave_dark\nLight :\n$catppuccin_light\n$dracula_light\n$gruvbox_light\n$nordic_light\n$solarized_light\n$vaporwave_light"

chosen="$(echo -e "$options" | dmenu -p "Tema menu " )"
case $chosen in

    $solarized_dark)

        THEME_GTK="NumixSolarizedDarkCyan"
        THEME_ICON="Numix-Circle"
        THEME_MODE="Solarized"
        COLOR_MODE="Dark"
        GTK_PREFER_DARK_MODE=1
        EMACS_THEME="doom-solarized-dark"
        WALLPAPER_LIGHTDM="LbI3B9z.jpeg"
    ;;
    $solarized_light)

        THEME_GTK="NumixSolarizedLightCyan"
        THEME_ICON="Numix-Circle-Light"
        THEME_MODE="Solarized"
        COLOR_MODE="Light"
        GTK_PREFER_DARK_MODE=0
        EMACS_THEME="doom-solarized-light"
        WALLPAPER_LIGHTDM="burst-light.png"

    ;;
    $gruvbox_dark)

        THEME_GTK="Gruvbox-Material-Dark"
        THEME_ICON="Numix-Circle"
        THEME_MODE="Gruvbox"
        COLOR_MODE="Dark"
        GTK_PREFER_DARK_MODE=1
        EMACS_THEME="doom-gruvbox"
        WALLPAPER_LIGHTDM="wallhaven-jxl8mw.jpg"
    ;;
    $gruvbox_light)

        THEME_GTK="Gruvbox-Plus-Light"
        THEME_ICON="Numix-Circle-Light"
        THEME_MODE="Gruvbox"
        COLOR_MODE="Light"
        GTK_PREFER_DARK_MODE=0
        EMACS_THEME="doom-gruvbox-light"
        WALLPAPER_LIGHTDM="gruv-takumi-drift.png"

    ;;
    $catppuccin_dark)

        THEME_GTK="Catppuccin-Frappe-Standard-Pink-Dark"
        THEME_ICON="Numix-Circle"
        THEME_MODE="Catppuccin"
        COLOR_MODE="Dark"
        GTK_PREFER_DARK_MODE=1
        EMACS_THEME='catppuccin) (setq catppuccin-flavor '"'"'frappe'
        WALLPAPER_LIGHTDM="CatppuccinMocha-Planets.png"

    ;;
    $catppuccin_light)

        THEME_GTK="Catppuccin-Latte-Standard-Sapphire-Light"
        THEME_ICON="Numix-Circle-Light"
        THEME_MODE="Catppuccin"
        COLOR_MODE="Light"
        GTK_PREFER_DARK_MODE=0
        EMACS_THEME='catppuccin) (setq catppuccin-flavor '"'"'latte'
        WALLPAPER_LIGHTDM="wp11912478-catppuccin-wallpapers.png"

    ;;
    $nordic_dark)

        THEME_GTK="Nordic-darker-v40"
        THEME_ICON="Numix-Circle"
        THEME_MODE="Nord"
        COLOR_MODE="Dark"
        GTK_PREFER_DARK_MODE=1
        EMACS_THEME="doom-nord"
        WALLPAPER_LIGHTDM="ign_unsplash15.png"

    ;;
    $nordic_light)

        THEME_GTK="Nordic-Polar-v40"
        THEME_ICON="Numix-Circle-Light"
        THEME_MODE="Nord"
        COLOR_MODE="Light"
        GTK_PREFER_DARK_MODE=0
        EMACS_THEME="doom-nord-light"
        WALLPAPER_LIGHTDM="ign_sunAndClouds.png"

	;;

    $dracula_dark)

        THEME_GTK="Dracula"
        THEME_ICON="Numix-Circle"
        THEME_MODE="Dracula"
        COLOR_MODE="Dark"
        GTK_PREFER_DARK_MODE=1
        EMACS_THEME="doom-dracula"
        WALLPAPER_LIGHTDM="base.png"
    ;;
    $dracula_light)

        THEME_GTK="Yaru-Pink-light"
        THEME_ICON="Numix-Circle-Light"
        THEME_MODE="Dracula"
        COLOR_MODE="Light"
        GTK_PREFER_DARK_MODE=0
        EMACS_THEME="doom-one-light"
        WALLPAPER_LIGHTDM="dracula-galaxy-6272a4.png"

	;;
    $vaporwave_dark)

        THEME_GTK="retrowave-glow"
        THEME_ICON="candy-icons"
        THEME_MODE="Vaporwave"
        COLOR_MODE="Dark"
        GTK_PREFER_DARK_MODE=1
        EMACS_THEME="rebecca"
        WALLPAPER_LIGHTDM="vaporwave005.jpg"

    ;;
    $vaporwave_light)


        THEME_GTK="Lavanda-Light"
        THEME_ICON="Numix-Circle-Light"
        THEME_MODE="Vaporwave"
        COLOR_MODE="Light"
        GTK_PREFER_DARK_MODE=0
        EMACS_THEME="rebecca"
        WALLPAPER_LIGHTDM="vaporwave009.jpg"
	;;

    *)
        exit 0
    ;;
esac

if [[ -z $chosen ]]; then
    exit 0
else
    # Arquivo variavel
    sed -i "s|^export THEME_MODE=.*|export THEME_MODE=\"$THEME_MODE\"|" ~/.theme_selected
    sed -i "s|^export COLOR_MODE=.*|export COLOR_MODE=\"$COLOR_MODE\"|" ~/.theme_selected

    # Altero as configuracoes do gtk
    # GTK2
    sed -i "s/^gtk-icon-theme-name =.*/gtk-icon-theme-name = \"$THEME_ICON\"/" ~/.config/gtk-2.0/gtkrc
    sed -i "s/^gtk-theme-name =.*/gtk-theme-name = \"$THEME_GTK\"/" ~/.config/gtk-2.0/gtkrc

    sed -i "s/^gtk-icon-theme-name=.*/gtk-icon-theme-name=\"$THEME_ICON\"/" ~/.gtkrc-2.0
    sed -i "s/^gtk-theme-name=.*/gtk-theme-name=\"$THEME_GTK\"/" ~/.gtkrc-2.0

    # GTK3
    sed -i "s/^gtk-theme-name=.*/gtk-theme-name=$THEME_GTK/" ~/.config/gtk-3.0/settings.ini
    sed -i "s/^gtk-icon-theme-name=.*/gtk-icon-theme-name=$THEME_ICON/" ~/.config/gtk-3.0/settings.ini
    sed -i "s/^gtk-application-prefer-dark-theme=.*/gtk-application-prefer-dark-theme=$GTK_PREFER_DARK_MODE/" ~/.config/gtk-3.0/settings.ini

    #Flatpak
    SUDO_ASKPASS=/usr/bin/ssh-askpsas sudo flatpak override --filesystem=$HOME/.themes
    SUDO_ASKPASS="$sudo_askpass" sudo flatpak override --env=GTK_THEME=$THEME_GTK

    # Suckless
    sed -i "s|^#include \"themes/.*|#include \"themes/${THEME_MODE,,}_${COLOR_MODE,,}.h\"|" ~/.config/suckless/dwm/config.def.h
    sed -i "s|^#include \"themes/.*|#include \"themes/${THEME_MODE,,}_${COLOR_MODE,,}.h\"|" ~/.config/suckless/st/config.def.h
    sed -i "s|^#include \"themes/.*|#include \"themes/${THEME_MODE,,}_${COLOR_MODE,,}.h\"|" ~/.config/suckless/dmenu/config.def.h
    sed -i "s|^#include \"themes/.*|#include \"themes/${THEME_MODE,,}_${COLOR_MODE,,}.h\"|" ~/.config/suckless/slock/config.def.h

    # Emacs Doom
    sed -i "s|(setq doom-theme .*)|(setq doom-theme '$EMACS_THEME)|" ~/.config/doom/config.el

    # Btop
    sed -i "s|^color_theme =.*|color_theme = \"${THEME_MODE,,}_${COLOR_MODE,,}\"|" ~/.config/btop/btop.conf

    # Lightdm
    SUDO_ASKPASS=/usr/bin/ssh-askpsas sudo cp -r ~/.icons/$THEME_ICON /usr/share/icons/
    SUDO_ASKPASS=/usr/bin/ssh-askpsas sudo cp -r ~/.themes/$THEME_GTK /usr/share/themes/
    SUDO_ASKPASS=/usr/bin/ssh-askpsas sudo cp -r ~/.wallpapers/$THEME_MODE/$COLOR_MODE/$WALLPAPER_LIGHTDM /usr/share/images/desktop-base/$WALLPAPER_LIGHTDM
    SUDO_ASKPASS=/usr/bin/ssh-askpsas sudo rm /etc/lightdm/lightdm-gtk-greeter.conf

    SUDO_ASKPASS=/usr/bin/ssh-askpsas sudo bash -c "cat > /etc/lightdm/lightdm-gtk-greeter.conf << EOF
[greeter]
background=/usr/share/images/desktop-base/$WALLPAPER_LIGHTDM
theme-name=$THEME_GTK
cursor-theme-name=capitaine-cursors-gruvbox-white
icon-theme-name=$THEME_ICON
default-user-image=/var/lib/AccountsService/icons/default.png
indicators=~a11y;~language;~spacer;~host;~clock;~spacer;~session;~power;
EOF"

   # Abre o dunst com o tema certo
    source $HOME/.theme_selected
    killall dunst
    dunst -conf "$HOME/.config/dunst/themes/${THEME_MODE}_${COLOR_MODE}" &
    dunstify "Aplicando tema" "Aguarde.." -h int:value:10  -i /usr/share/icons/ePapirus/16x16/status/package-reinstall.svg

    # Fecha programas systray
    killall copyq
    killall solaar
    killall slock

    # Compila dwm
    cd $HOME/.config/suckless/dwm
    rm config.h
    make
    SUDO_ASKPASS="$sudo_askpass" sudo make clean install

    dunstify "Aplicando tema" "Aguarde.." -h int:value:40 -i /usr/share/icons/ePapirus/16x16/status/package-reinstall.svg

    # Compila st
    cd $HOME/.config/suckless/st
    rm config.h
    make
    SUDO_ASKPASS="$sudo_askpass" sudo make clean install

    dunstify "Aplicando tema" "Aguarde.." -h int:value:60 -i /usr/share/icons/ePapirus/16x16/status/package-reinstall.svg

    # Compila dmenu
    cd $HOME/.config/suckless/dmenu
    rm config.h
    make
    SUDO_ASKPASS="$sudo_askpass" sudo make clean install

    # Compila slock
    cd $HOME/.config/suckless/slock
    rm config.h
    make
    SUDO_ASKPASS="$sudo_askpass" sudo make clean install

    dunstify "Aplicando tema" "Aguarde.." -h int:value:80 -i /usr/share/icons/ePapirus/16x16/status/package-reinstall.svg
    sleep 0.8
    # Faz sincronizacao do doom
    #$HOME/.config/emacs/bin/doom sync

    dunstify "Aplicando tema" "Aguarde.." -h int:value:99 -i /usr/share/icons/ePapirus/16x16/status/package-reinstall.svg

    # Restart dwm
    xdotool key Super_L+shift+r

    dunstify "Pronto" "Aplicação do tema finalizado!!!" -h int:value:100 -i /usr/share/icons/ePapirus/16x16/status/package-install.svg
fi
