#!/bin/bash

### Requisitos
### sudo pacman -S bitwarden-rofi bitwarden-cli
###
### Iniciar configuracao do bitwarden-cli
### bitwarden-cli login

source ~/.theme_selected
arquivo=$(echo ~/.dotfiles/.config/rofi/themes/${THEME_MODE}_${COLOR_MODE}.rasi | tr '[:upper:]' '[:lower:]')

$HOME/.config/suckless/scripts/others/bwmenu -- -m -4 -modi 'window,drun,ssh,combi' -font 'CaskaydiaMono Nerd Font 14' -show drun -icon-theme 'Papirus-Dark' -show-icons -theme $arquivo
