#!/bin/bash

# Carrega o player atual
source ~/.cache/playerctl_selecionado

# Roda o comando
playerctl --player=$PLAYER_SELECIONADO previous

# Envia notificacao
~/.local/bin/playerctl_songinfo

# Atualiza dwmblocks
kill -35 $(pidof dwmblocks)
