#!/bin/bash

# funcoes cliclaveis
case $BUTTON in
    3) SUDO_ASKPASS=/usr/bin/ssh-askpass sudo synaptic-pkexec ;;
	6) setsid -f st -e emacs -nw "$0" ;;
esac

icon="^c#6c71c4^󱧕^d^"

updates=$(apt list --upgradable 2>/dev/null | grep -c 'upgradable')

if [ "$updates" -eq 0 ]; then
    echo "$icon 0  "
else
    echo "$icon $updates  "
    notify-send -i "/usr/share/icons/Adwaita/24x24/legacy/software-update-available.png" "󱧕 Atualização Disponível" "Existem <b>$updates</b> atualizações disponíveis."
fi
