/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_alternativetags.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_winicon.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "floatpos.h"
#include "pertag.h"
#include "restartsig.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "setborderpx.h"
#include "shift.h"
#include "shifttag.h"
#include "shifttagclients.h"
#include "shiftview.h"
#include "shiftviewclients.h"
#include "stacker.h"
#include "sticky.h"
#include "swallow.h"
#include "vanitygaps.h"
#include "xrdb.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_bstackhoriz.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_flextile-deluxe.h"
#include "layout_gapplessgrid.h"
#include "layout_grid.h"
#include "layout_horizgrid.h"
#include "layout_monocle.h"
#include "layout_nrowgrid.h"
#include "layout_tile.h"

